# Generated by Django 4.0.5 on 2022-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_division_div_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='elevation',
            field=models.FloatField(null=True),
        ),
    ]
