# Generated by Django 4.0.5 on 2022-07-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(choices=[('KUCHING', 'Kuching'), ('SRI AMAN', 'Sri Aman'), ('SARIKEI', 'Sarikei'), ('KAPIT', 'Kapit'), ('SIBU', 'Sibu'), ('BINTULU', 'Bintulu'), ('MIRI', 'Miri'), ('LIMBANG', 'Limbang'), ('LAWAS', 'Lawas')], default='KUCHING', max_length=100)),
                ('div_img', models.ImageField(blank=True, null=True, upload_to='div_img/', verbose_name='Division image')),
                ('population', models.IntegerField()),
                ('area', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['population'],
            },
        ),
    ]
